# Generated by Django 4.2.27 on 2026-02-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expenseCost',
            new_name='ExpenseCost',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expenseDate',
            new_name='ExpenseDate',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expenseItem',
            new_name='ExpenseItem',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='noteDate',
            new_name='NoteDate',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='userId',
            new_name='UserId',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Fullname',
            new_name='FullName',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='regDate',
            new_name='RegDate',
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('salary', models.FloatField(default=0)),
                ('expenses', models.FloatField(default=0)),
                ('monthly_savings', models.FloatField(default=0)),
                ('total_savings', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.userdetail')),
            ],
        ),
    ]
