# Generated by Django 4.2.27 on 2026-02-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_expensecost_expense_expensecost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='MySalary',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
