# Generated by Django 4.2.27 on 2026-02-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_userdetail_mysalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='monthly_savings',
            new_name='balance',
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalary',
            unique_together={('user', 'month')},
        ),
    ]
